### ISSUE TITLE
Entries in DB with date 1970-01-20

### ISSUE THREAD

**Issue by guidosch** [guidosch/bikecounter#80]
There are many entries in the DB with timestamp=0. Couting showed something like 30 entires only for antennentrail-1.
We may should also send the timestamp from TTN to have an idea when this happens.

<img width="1226" alt="Bildschirm­foto 2023-02-17 um 22 20 59" src="https://user-images.githubusercontent.com/3204954/219796495-b2173e87-8096-4171-92c5-4fc0218f1f2f.png">

**Comment by guidosch** [comment]
Dates are not 0 but 1970-01-20, hmmm even more strange.

**Comment by guidosch** [comment]
Not only Antennentrail but also all the others with latest software version.

**Comment by MeierTobias** [comment]
I think this problem is already solved. 
The first package of the device is the time synchronization message. This contains a wrong timestamp (uninitialized) which triggers the cloud function to send a downlink message with the correction parameter. I updated the cloud function to check if the received message is a sync message and if so to not save it into the DB. But I think this change was applied a few weeks after the software update due to the lack of permissions to edit the cloud functions. 
I think these values are artifacts from that period where the cloud function did not handle that special case.

So I would say it is save to delete these entries.

**Comment by MeierTobias** [comment]
Related fix #62

**Comment by guidosch** [comment]
Deleted timestamps with year 1970. Closing issue.
